# Generated by Django 4.2.11 on 2025-03-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
